# Generated by Django 2.0 on 2019-05-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='step_1',
            new_name='step1',
        ),
    ]
