# Generated by Django 2.0 on 2019-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190604_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
