# Generated by Django 2.0 on 2019-06-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190604_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='recipeName',
        ),
    ]
