# Generated by Django 2.0 on 2019-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_comment_pubdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
