# Generated by Django 2.0 on 2019-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('videoID', models.CharField(blank=True, max_length=256)),
                ('recipeName', models.CharField(max_length=256, unique=True)),
                ('material', models.TextField()),
                ('step_1', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
