# Generated by Django 2.0 on 2019-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190528_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
