# Generated by Django 2.2 on 2019-06-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190529_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
